# Generated by Django 4.0.3 on 2022-03-07 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clothe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_type', models.CharField(choices=[('Undefined Type', 'Undefined'), ('Shirt', 'Shirt'), ('Pants', 'Pants'), ('Shoes', 'Shoes')], default='Undefined Type', max_length=200)),
                ('size', models.CharField(choices=[('Undefined Size', 'Undefined'), ('Large', 'L'), ('Small', 'S'), ('ExtraLarge', 'Xl'), ('ExtraSmall', 'Xs')], default='Undefined Size', max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField(default=0)),
                ('slug', models.SlugField()),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='media')),
                ('in_stock', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Stash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.IntegerField(default=0)),
                ('items', models.ManyToManyField(to='core.clothe')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('total_price', models.IntegerField()),
                ('ordered', models.BooleanField(default=False)),
                ('items', models.ManyToManyField(to='core.clothe')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
