# Generated by Django 4.0.3 on 2022-03-07 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_orderitem_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stash',
            name='total_price',
        ),
    ]
